[ndk][conf] Python: AC_PATH_PROG -> AC_PATH_PROGS and fix search order
.. to python26 python2 python as some distros have python == python3

Change-Id: I2e1fbb6aa23614abc6df1581097400a31b7badac

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8302,8 +8302,10 @@ else
 echo "$as_me: WARNING: specified python ($PYTHON) is not usable, searching path" >&2;}
   fi
 
-  # Extract the first word of "python python2 python27", so it can be a program name with args.
-set dummy python python2 python27; ac_word=$2
+  for ac_prog in python27 python2 python
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
 if test "${ac_cv_path_PYTHON+set}" = set; then
@@ -8329,11 +8331,6 @@ done
 done
 IFS=$as_save_IFS
 
-  test -z "$ac_cv_path_PYTHON" && ac_cv_path_PYTHON="{ echo "$as_me:$LINENO: result: not found" >&5
-echo "${ECHO_T}not found" >&6; }
-                { { echo "$as_me:$LINENO: error: could not find python 2.7 or higher" >&5
-echo "$as_me: error: could not find python 2.7 or higher" >&2;}
-   { (exit 1); exit 1; }; }"
   ;;
 esac
 fi
@@ -8346,6 +8343,14 @@ else
 echo "${ECHO_T}no" >&6; }
 fi
 
+
+  test -n "$PYTHON" && break
+done
+test -n "$PYTHON" || PYTHON="{ echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6; }
+                { { echo "$as_me:$LINENO: error: could not find python 2.7 or higher" >&5
+echo "$as_me: error: could not find python 2.7 or higher" >&2;}
+   { (exit 1); exit 1; }; }"
 
 fi
 
